# CMake generated Testfile for 
# Source directory: /Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests
# Build directory: /Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/build_alembic/lib/Alembic/AbcGeom/Tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(AbcGeom_PolyMesh_TEST "AbcGeom_PolyMeshTest")
set_tests_properties(AbcGeom_PolyMesh_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;43;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_HelperLib_TEST "AbcGeom_HelperLibTest")
set_tests_properties(AbcGeom_HelperLib_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;48;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_Points_TEST "AbcGeom_PointsTest")
set_tests_properties(AbcGeom_Points_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;53;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_Nurbs_TEST "AbcGeom_NurbsTest")
set_tests_properties(AbcGeom_Nurbs_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;60;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_SubD_TEST "AbcGeom_SubDTest")
set_tests_properties(AbcGeom_SubD_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;67;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_SubDFaceSet_TEST "AbcGeom_SubDFaceSetTest")
set_tests_properties(AbcGeom_SubDFaceSet_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;74;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_SchemaMatching_TEST "AbcGeom_SchemaMatchingTest")
set_tests_properties(AbcGeom_SchemaMatching_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;79;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_Xform_TEST "AbcGeom_XformTest")
set_tests_properties(AbcGeom_Xform_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;84;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_Xform2_TEST "AbcGeom_XformTest2")
set_tests_properties(AbcGeom_Xform2_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;89;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_Curves_TEST "AbcGeom_CurvesTest")
set_tests_properties(AbcGeom_Curves_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;96;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_GeomBase_TEST "AbcGeom_GeomBaseTest")
set_tests_properties(AbcGeom_GeomBase_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;103;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_TransformingMesh_TEST "AbcGeom_TransformingMeshTest")
set_tests_properties(AbcGeom_TransformingMesh_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;110;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_CompileTest_TEST "AbcGeom_CompileTest")
set_tests_properties(AbcGeom_CompileTest_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;115;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_LightTest_TEST "AbcGeom_LightTest")
set_tests_properties(AbcGeom_LightTest_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;120;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
add_test(AbcGeom_Camera_TEST "AbcGeom_CameraTest")
set_tests_properties(AbcGeom_Camera_TEST PROPERTIES  _BACKTRACE_TRIPLES "/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;125;ADD_TEST;/Users/brandondiaz/Downloads/CS/cs2240/cs2240-final-project/alembic/lib/Alembic/AbcGeom/Tests/CMakeLists.txt;0;")
